import { db } from '@/db';
import { stockMovements } from '@/db/schema';

async function main() {
    const sampleStockMovements = [
        {
            itemType: 'materiau',
            itemId: 1,
            userId: 2,
            action: 'retrait',
            quantity: 20,
            date: '2024-01-05T08:30:00.000Z',
            notes: 'Pour chantier Bordeaux - dalle béton',
        },
        {
            itemType: 'materiel',
            itemId: 3,
            userId: 3,
            action: 'retrait',
            quantity: 2,
            date: '2024-01-08T09:15:00.000Z',
            notes: 'Chantier Lyon - montage façade',
        },
        {
            itemType: 'materiau',
            itemId: 2,
            userId: 2,
            action: 'retrait',
            quantity: 15,
            date: '2024-01-12T07:45:00.000Z',
            notes: 'Préparation mortier chantier Toulouse',
        },
        {
            itemType: 'materiau',
            itemId: 1,
            userId: 3,
            action: 'retour',
            quantity: 5,
            date: '2024-01-15T16:20:00.000Z',
            notes: 'Surplus chantier Lyon',
        },
        {
            itemType: 'materiel',
            itemId: 5,
            userId: 2,
            action: 'retrait',
            quantity: 1,
            date: '2024-01-18T08:00:00.000Z',
            notes: 'Démolition mur porteur - chantier Marseille',
        },
        {
            itemType: 'materiau',
            itemId: 4,
            userId: 3,
            action: 'retrait',
            quantity: 8,
            date: '2024-01-20T10:30:00.000Z',
            notes: 'Coulage plancher chantier Nice',
        },
        {
            itemType: 'materiau',
            itemId: 2,
            userId: 2,
            action: 'ajout',
            quantity: 30,
            date: '2024-01-22T14:00:00.000Z',
            notes: 'Livraison fournisseur Batimex',
        },
        {
            itemType: 'materiel',
            itemId: 7,
            userId: 3,
            action: 'suppression',
            quantity: 1,
            date: '2024-01-25T11:45:00.000Z',
            notes: 'Équipement HS - mise au rebut',
        },
        {
            itemType: 'materiau',
            itemId: 6,
            userId: 2,
            action: 'retrait',
            quantity: 12,
            date: '2024-01-28T09:00:00.000Z',
            notes: 'Isolation thermique chantier Nantes',
        },
        {
            itemType: 'materiel',
            itemId: 2,
            userId: 3,
            action: 'retour',
            quantity: 1,
            date: '2024-02-01T17:30:00.000Z',
            notes: 'Fin de chantier Bordeaux',
        },
        {
            itemType: 'materiau',
            itemId: 8,
            userId: 2,
            action: 'ajout',
            quantity: 25,
            date: '2024-02-03T13:15:00.000Z',
            notes: 'Réapprovisionnement stock - commande urgente',
        },
        {
            itemType: 'materiel',
            itemId: 9,
            userId: 3,
            action: 'retrait',
            quantity: 3,
            date: '2024-02-05T08:30:00.000Z',
            notes: 'Travaux électriques chantier Strasbourg',
        },
        {
            itemType: 'materiau',
            itemId: 10,
            userId: 2,
            action: 'retrait',
            quantity: 18,
            date: '2024-02-08T10:00:00.000Z',
            notes: 'Revêtement sol chantier Lille',
        },
        {
            itemType: 'materiel',
            itemId: 4,
            userId: 3,
            action: 'retour',
            quantity: 2,
            date: '2024-02-10T16:00:00.000Z',
            notes: 'Retour matériel après inspection',
        },
        {
            itemType: 'materiau',
            itemId: 12,
            userId: 2,
            action: 'ajout',
            quantity: 40,
            date: '2024-02-12T14:30:00.000Z',
            notes: 'Livraison mensuelle fournisseur principal',
        },
        {
            itemType: 'materiel',
            itemId: 11,
            userId: 3,
            action: 'retrait',
            quantity: 1,
            date: '2024-02-15T09:00:00.000Z',
            notes: 'Démolition cloison chantier Cannes',
        },
        {
            itemType: 'materiau',
            itemId: 14,
            userId: 2,
            action: 'retrait',
            quantity: 22,
            date: '2024-02-18T11:30:00.000Z',
            notes: 'Pose parquet appartement Rennes',
        },
        {
            itemType: 'materiau',
            itemId: 15,
            userId: 3,
            action: 'ajout',
            quantity: 35,
            date: '2024-02-20T15:00:00.000Z',
            notes: 'Réception livraison enduit façade',
        },
        {
            itemType: 'materiel',
            itemId: 13,
            userId: 2,
            action: 'retrait',
            quantity: 3,
            date: '2024-02-23T08:45:00.000Z',
            notes: 'Assemblage meuble chantier Montpellier',
        },
        {
            itemType: 'materiau',
            itemId: 16,
            userId: 3,
            action: 'retrait',
            quantity: 15,
            date: '2024-02-26T10:15:00.000Z',
            notes: 'Pose carrelage salle de bain Grenoble',
        },
        {
            itemType: 'materiel',
            itemId: 14,
            userId: 2,
            action: 'retour',
            quantity: 1,
            date: '2024-03-01T17:00:00.000Z',
            notes: 'Fin travaux démolition Toulon',
        },
        {
            itemType: 'materiau',
            itemId: 18,
            userId: 3,
            action: 'retrait',
            quantity: 28,
            date: '2024-03-04T09:30:00.000Z',
            notes: 'Charpente toiture chantier Lille',
        },
        {
            itemType: 'materiel',
            itemId: 16,
            userId: 2,
            action: 'suppression',
            quantity: 1,
            date: '2024-03-06T14:00:00.000Z',
            notes: 'Chalumeau défectueux - mise au rebut',
        },
        {
            itemType: 'materiau',
            itemId: 19,
            userId: 3,
            action: 'ajout',
            quantity: 150,
            date: '2024-03-08T13:00:00.000Z',
            notes: 'Arrivage ferraillage pour dalle',
        },
        {
            itemType: 'materiel',
            itemId: 18,
            userId: 2,
            action: 'retrait',
            quantity: 1,
            date: '2024-03-10T08:30:00.000Z',
            notes: 'Découpe carrelage chantier Cannes',
        },
        {
            itemType: 'materiau',
            itemId: 20,
            userId: 3,
            action: 'retrait',
            quantity: 12,
            date: '2024-03-12T11:00:00.000Z',
            notes: 'Finitions joints sanitaires',
        },
        {
            itemType: 'materiel',
            itemId: 20,
            userId: 2,
            action: 'retrait',
            quantity: 1,
            date: '2024-03-15T07:45:00.000Z',
            notes: 'Excavation terrain chantier Strasbourg',
        },
        {
            itemType: 'materiau',
            itemId: 22,
            userId: 3,
            action: 'retrait',
            quantity: 30,
            date: '2024-03-18T10:30:00.000Z',
            notes: 'Carrelage mural salle de bain Lyon',
        },
        {
            itemType: 'materiau',
            itemId: 23,
            userId: 2,
            action: 'retrait',
            quantity: 180,
            date: '2024-03-20T09:00:00.000Z',
            notes: 'Construction piscine Marseille',
        },
        {
            itemType: 'materiel',
            itemId: 19,
            userId: 3,
            action: 'retour',
            quantity: 2,
            date: '2024-03-22T16:30:00.000Z',
            notes: 'Retour décapeuse après rénovation',
        },
    ];

    await db.insert(stockMovements).values(sampleStockMovements);
    
    console.log('✅ Stock movements seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});